no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: http://mock-oauth2-server:1111/v2.0/.well-known/openid-configuration
    accepted_audience: api://${MOTTAK_CLIENT_ID}/.default
    cookie_name: azure_token
  issuer.selvbetjening:
    discoveryurl: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
    accepted_audience: ${ACCEPTEDAUDIENCE}
    cookie_name: selvbetjening-idtoken
  client:
    registration:
      ba-sak-clientcredentials:
        resource-url: ${FAMILIE_BA_SAK_API_URL}
        token-endpoint-url: http://mock-oauth2-server:1111/v2.0/token
        grant-type: client_credentials
        scope: ${MOTTAK_BA_SAK_SCOPE}
        authentication:
          client-id: ${MOTTAK_CLIENT_ID}
          client-secret: ${MOTTAK_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      integrasjoner-clientcredentials:
        resource-url: ${FAMILIE_INTEGRASJONER_API_URL}
        token-endpoint-url: http://mock-oauth2-server:1111/v2.0/token
        grant-type: client_credentials
        scope: ${MOTTAK_FAMILIE_INTEGRASJONER_SCOPE}
        authentication:
          client-id: ${MOTTAK_CLIENT_ID}
          client-secret: ${MOTTAK_CLIENT_SECRET}
          client-auth-method: client_secret_basic

prosessering:
  fixedDelayString.in.milliseconds: 3000

spring:
  cloud:
    vault:
      database:
        role: familie
  datasource:
    url: jdbc:postgresql://postgres-mottak:5432/familiebamottak
    hikari:
      username: familie
      password: familie-pwd
  flyway:
    enabled: true

funksjonsbrytere:
  enabled: false
  unleash:
    uri: http://dummy/api/
    cluster: lokalutvikling
    applicationName: familie-ba-mottak

logging:
  level:
    org: INFO
    no.nav: DEBUG
#  config: "classpath:logback-test.xml"

FAMILIE_BA_DOKGEN_API_URL: http://familie-ba-dokgen:8080
FAMILIE_BA_SAK_API_URL: http://familie-ba-sak:8089/api
FAMILIE_INTEGRASJONER_API_URL: http://familie-integrasjoner:8085/api

FØDSELSHENDELSE_VENT_PÅ_TPS_MINUTTER: 0
FØDSELSHENDELSE_REKJØRINGSINTERVALL_MINUTTER: 0

JOURNALFOERINGHENDELSE_V1_TOPIC_URL: aapen-dok-journalfoering-v1-e2e
NORG2_API_URL: http://familie-mock-server:1337/rest/api/norg2